name: location_marker_example
description: Example of FlutterMapLocationMarkerPlugin
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.16.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_compass:
    path: ../../flutter_compass
  flutter_joystick: ^0.0.3
  flutter_map: any
  flutter_map_location_marker:
    path: ../
  geolocator: any
  latlong2: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any

flutter:
  uses-material-design: true
